### PR TITLE
Fix eslint packages to have correct peerDeps/deps

### PR DESCRIPTION
**Pull request by kaylieEB**
Some packages that should have been hard dependencies were in peer, and packages that were extending from other packages were requesting the sub-dependencies as its own peer, so this diff is correcting that.

### CODE REVIEW

**Comment by kaylieEB** [comment]
@BenAtEventbrite @gagoar I'm rethinking this approach and this might need more discussion.
The original issue came from core:
```
warning "eslint-config-eventbrite@4.1.0" has unmet peer dependency "babel-eslint@^7.0.0".
warning "eslint-config-eventbrite@4.1.0" has incorrect peer dependency "eslint@^3.0.0".
warning "eslint-config-eventbrite@4.1.0" has unmet peer dependency "eslint-plugin-import@^2.0.0".
warning "eslint-config-eventbrite-legacy@3.0.0" has incorrect peer dependency "eslint@^3.0.0".
```
The issue with these packages being peerDeps, as plugins generally are, is that we want a single copy at top level. But with yarn's flat structure, dependencies are already deduped at the root level, avoiding the need to define these, and some package seem to [adopt this model](https://github.com/facebook/jest/blob/master/packages/eslint-config-fb-strict/package.json). This also solves the issue if we down the road we end up adding a conflicting eslint config/plugin (although that's less likely). But alternatively, we can just add all the peers to core as a dev dependency, or to loosen the requirements to be >=, example.

**Comment by kaylieEB** [comment]
the only thing that might need to change is `babel-eslint`, i.e., should the configuration dictate which parser to use?

**Comment by benmvp** [comment]
The configuration does depend on a certain parser to work, but it can likely be more relaxed than what the current peer dependency setting is. Generally peer dependencies can use `>=` vs. `^` because they only depend on little bits

**Comment by kaylieEB** [comment]
per offline convo, closing this and moving this to core.

**Pull request closed without merging**
